name: Publish Package to PyPi
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install build
        run: python -m pip install build
      - name: Build distribution
        run: python -m build
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}